#!/bin/bash

echo "Enter first number:"
read num1
echo "Enter second number:"
read num2
echo "Enter operation (+,-,*,/):"
read operation

case $operation in 
	+) result=$((num1 + num2));;
	-) result=$((num1 - num2));;
	\*) result=$((num1 * num2));;
	/)
		if [ $num2 -eq 0 ]
		then 
			echo "Error: Division by zero is not allowed"
			exit 1
		else
			result=$((num1 / num2))
		fi
		;;
	*) echo "Error: Invalid opeartion."
	exit 1
esac

echo "The result is $result"
