#!/bin/bash 

while true 
do 
	echo "Enter the first number (or type exit to quit):"
	read num1

	if [ "$num1" = "exit" ]
	then 
		break 
	fi

	echo "Enter the second number (or type ext to quit):"
	read num2

	if [ "$num2" = "exit" ]
	then 
		break 
	fi 
	
	echo "Enter the operation (+, -, *, /):"
	read operation 

	case $operation in 
 		+) result=$((num1 + num2)) ;;
		-) result=$((num1 - num2)) ;;
		\*) result=$((num1 * num2)) ;;
		/)
			if [ $num2 -eq 0]
			then 
				echo "Error: division by zero is not allowed."
				continue 
			else 
				result=$((num1 / num2))
			fi
			;;
		*) echo "Error: invalid operation."
			continue 
	esac 
	echo "The result is $result"
done 	
